FROM ubuntu:22.04 AS without-onbuild

RUN echo "This an echo before ONBUILD instruction in the Dockerfile.onbuild file."

FROM without-onbuild AS with-onbuild

ONBUILD ARG MODE_PROD=""
ONBUILD ENV MODE_PROD=${MODE_PROD}
