name: Generate base image with onbuild

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: read
  packages: write
  pull-requests: read
  id-token: write

jobs:
  docker-build-first-image:
    uses: hoverkraft-tech/ci-github-container/.github/workflows/docker-build-images.yml@0.26.0
    secrets:
      # Password or GitHub token (packages:read and packages:write scopes) used to log against the OCI registry.
      # See https://github.com/docker/login-action#usage.
      oci-registry-password: ${{ secrets.GITHUB_TOKEN }}
    with:
      runs-on: '["ubuntu-latest"]'
      oci-registry: "ghcr.io"
      images: |-
        [
          {
              "name": "without-onbuild",
              "context": ".",
              "target": "without-onbuild",
              "dockerfile": "./docker/Dockerfile.onbuild",
            "platforms": ["linux/amd64"]
          },
          {
              "name": "with-onbuild",
              "context": ".",
              "target": "with-onbuild",
              "dockerfile": "./docker/Dockerfile.onbuild",
            "platforms": ["linux/amd64"]
          }
        ]
