name: Debug docker buildx gha backend onbuild run

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  packages: write
  pull-requests: read
  id-token: write

jobs:
  docker-build-first-image:
    uses: hoverkraft-tech/ci-github-container/.github/workflows/docker-build-images.yml@0.26.0
    env:
      DOCKER_FILE: ./docker/Dockerfile
    secrets:
      # Password or GitHub token (packages:read and packages:write scopes) used to log against the OCI registry.
      # See https://github.com/docker/login-action#usage.
      oci-registry-password: ${{ secrets.GITHUB_TOKEN }}
    with:
      runs-on: '["ubuntu-latest"]'
      oci-registry: "ghcr.io"
      images: |
        [
          {
              "name": "application",
              "context": ".",
              "dockerfile": "${{ env.DOCKER_FILE }}",
              "target": "prod",
            "platforms": [
              "linux/amd64",
            ]
          }
        ]
